#define VM_PPOBITS 12
#define VM_PPOMASK 0xFFF
#define VM_PPNMASK 0x7FFFFFFFFFFFF000

#define VM_PAGEDOUT 0xDEADBEEF
#define VM_PAGESIZE 0x1000 

#define VM_MINADDR 0x1000

#define VM_PMEMSIZE 0xF000

#define VM_PTABBITS 9
#define VM_PTABSIZE ((1<<VM_PTABBITS))

#define VM_PTABLEVS 4

#define VM_INACTIVESIZE 16
#define VM_ACTIVESIZE 16
